[[questions]]
type = "ShortAnswer"
prompt.prompt = "Wie heißt die SQL-Aggregatfunktion zum Zählen von Zeilen (ohne Klammern)?"
answer.answer = "COUNT"
context = "Kapitel 6: Aggregierung"
id = "dc6bcfdf-b8c5-493c-bfd6-1ee13cfd3f56"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Wie heißt die SQL-Aggregatfunktion für den Durchschnitt (ohne Klammern)?"
answer.answer = "AVG"
context = "Kapitel 6: Aggregatfunktionen"
id = "72f4ec1e-63ac-4f98-be64-cf4ee6f6f8d9"

[[questions]]
type = "ShortAnswer"
prompt.prompt = "Wie heißt die SQL-Aggregatfunktion für den größten Wert (ohne Klammern)?"
answer.answer = "MAX"
context = "Kapitel 6: Aggregatfunktionen"
id = "f3ea78df-4f8d-4485-b13f-e34ed3d47328"

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Welche Aggregatfunktion berechnet den Durchschnitt?"
prompt.distractors = [
	"SUM",
	"MIN",
	"COUNT"
]
answer.answer = "AVG"
context = "AVG berechnet den Mittelwert der Werte einer Spalte."
id = "0bdf7f6f-6ec1-44ca-93ef-ec1efe62257d"

[[questions]]
type = "Tracing"
prompt.program = """
SELECT AVG()
FROM fahrraeder;
"""
answer.doesCompile = false
context = "AVG benötigt einen Ausdruck oder Spaltennamen in den Klammern."
id = "774862db-0898-44ec-88f3-54f8fcafbc57"
